### ISSUE TITLE
Problems with the visual editor

### ISSUE THREAD

**Issue by MondoXwan** [xBourner/status-card#14] opened 2024-11-23 11:14 UTC
The visual editor on my dashboard doesn't work at all. As soon as I try to change a switch, it resets itself. This applies to all switches.
In the code editor, I was at least able to make some of the adjustments.
However, the sort order doesn't work in the code editor either, and I can't hide the connectivity either. 

[v2.2.0](https://github.com/xBourner)

**Comment by xBourner** [comment] 2024-11-23 15:41
on what device you have HA installed and how? what is your browser? everything up to date?
do you get any errors in your dev console?

press F12 to open dev tools in browser and go to console. you should see some entries

**Comment by danielrudolf** [comment] 2024-11-24 08:20
I have the same problem. Everything is up to date. It does not work on several browsers and HA runs on a Rapsi 5.

**Comment by xBourner** [comment] 2024-11-24 09:15
> I have the same problem. Everything is up to date. It does not work on several browsers and HA runs on a Rapsi 5.

Any more info from dev tools where the issue exactly happens? I can't reproduce any issues on my side.

**Comment by mainzerp** [comment] 2024-11-25 10:20
Having the same problem.
HA: 2024.11.3
Latest Chrome

It seems that the switches are read only in the visual editor.

Debug from Chrome:
TypeError: "showPerson" is read-only
    toggleSetting status-card.js:2
    renderSettings status-card.js:17
    renderHaForm status-card.js:8
    handleEvent status-card.js:2
    n fire_event.ts:76
    value ha-form.ts:211
    n fire_event.ts:76
    value ha-selector-boolean.ts:47
    handleEvent lit-html.ts:2018
    firstUpdated mwc-switch-base.ts:121

**Comment by xBourner** [comment] 2024-11-26 17:03
> Having the same problem. HA: 2024.11.3 Satus-Card: v2.2.1 Latest Firefox

Strange. I also tested it with latest firefox release and i have no trouble at all. Everything works as expected and not a single error in dev tools. I don't know how to fix this if i can't reproduce it.

**Comment by xBourner** [comment] 2024-11-29 17:56
I made some changes in my dev card which  i want to use to troubleshoot some things.

here are some instructions to add a .js as a new card copied from another issue:

Instructions for Dev Card:

First you need do download/make a new file with the content of teh dev-card. Its located here: https://github.com/xBourner/status-card/blob/main/test/dev-status-card.js (please make sure its a .js and not a .js.txt or something else)

When this is done you need to find where your config folder is located. There a several ways to get to this.
The easiest would be to add the samba add on and access your folder from your explorer via //IP-of-HA/config
But you can also add a new file via file editor or visual studio code.

Make sure your new file is located in /config/www. So the full path would be //IP-of-HA/config/config/www/dev-status-card.js

Ater all this the last part is to add it to your dashboard. Go to your HA dashboard. Go to Settings -> Dashboards -> Three Dots in the Top Right Corner -> Resources. Here you click Add Resource. Add the string /local/dev-status-card.js

All you need to do now is to add a new custom card. Go to one dashboard. Add a card and add a type: custom:dev-status-card

Im pretty sure finding and adding the file to your config folder is the hardest part as a new user. maybe you need to google to find out how to access the config folder. but its a common practice so i just did a small part on this.

If you were able to add it please send me some screenshots of the dev console. also please tell me if your card works if you just add it and stops working if you change something via editor.

@mainzerp please tell me if this fixes it for you. i really dont what to do because i can't reproduce it. but maybe with some screenshots/dev console output i can come a bit closer.

**Comment by mainzerp** [comment] 2024-11-29 18:12
The card works, its only not editable via gui.

Sill the same error.

![error](https://github.com/user-attachments/assets/3dc22eb3-60c6-4842-b352-4eda520ba041)

**Comment by xBourner** [comment] 2024-11-29 18:39
> The card works, its only not editable via gui.
> 
> Sill the same error.

Ok, every setting or just the toggles on top like showPerson and showPersonName?

Also updated the function to handle these toggles in the dev card. hopefully it works now.
make sure to edit the ressource and add a ?v=1 behind the string to avoid caching problems

**Comment by mainzerp** [comment] 2024-11-29 18:57
The Filter Section works via gui, everything else (toggle or drop down) switches back to default/empty instantly.

![grafik](https://github.com/user-attachments/assets/91964eb1-90d4-4f65-b4f0-36e7be5b692a)

**Comment by mainzerp** [comment] 2024-11-29 19:18
My fault, didnt used the latest dev-status-card.js you just updated :D Toggles now woking.

![grafik](https://github.com/user-attachments/assets/cc851e0c-cbe0-4816-9247-bbce65798ec0)

Everything below the filter section is sill not working.

**Comment by xBourner** [comment] 2024-11-29 19:24
> My fault, didnt used the latest dev-status-card.js you just updated :D Toggles now woking.

great. we are doing this step by step. any other errors in your console from dev tools when opening a dropdown?
also filter is also a dropdown do you mean this?

**Comment by mainzerp** [comment] 2024-11-29 19:31
The toggles and drop downs in the filter filter section and above are working.

![grafik](https://github.com/user-attachments/assets/7d4804eb-314b-47e7-b89d-f86e84322ca0)

Domains/Device Class
Extra Entities
Remove Entities
are not woking.

![grafik](https://github.com/user-attachments/assets/897521b0-27d7-4796-8ae4-70f927e614b3)
![grafik](https://github.com/user-attachments/assets/4dab39ec-7656-45b2-b2a1-d402452cbc4e)

**Comment by xBourner** [comment] 2024-11-29 20:25
> The toggles and drop downs in the filter filter section and above are working.

okay i hope this is also fixed now. please check the latest dev card and look if this is working for you (at least the settings for domains) and please check if every single one works. updating colors was a bit different so maybe this wont work for you.

if there is still an error please post it too. but lets look at the domains settings first and after that the next one

**Comment by xBourner** [comment] 2024-11-29 21:12
> Domain/device class section is now fully working :)

very nice. i updated the dev file again. please try it. not sure if extra entities are working. had some problems again with the color function.

**Comment by mainzerp** [comment] 2024-11-29 21:15
Everything is working now :)

![grafik](https://github.com/user-attachments/assets/85fd919f-af58-4441-92a7-72ef5ea5c8b0)

**Comment by xBourner** [comment] 2024-11-29 21:17
> Everything is working now :)

Great i will make the changes in the card itself and will publish a new build.
Danke für deine Hilfe, das hätte ich sonst nie so schnell hinbekommen!

**Comment by xBourner** [comment] 2024-11-29 21:33
@mainzerp @MondoXwan @danielrudolf please check if the errors are gone with the latest release https://github.com/xBourner/status-card/releases/tag/v2.3.1

**Comment by mainzerp** [comment] 2024-11-29 21:39
For me, everything is working as it should with 2.3.1

**Closed** 2024-12-27 09:35 UTC
